### ISSUE TITLE
Suplir una duda

### ISSUE THREAD

**Issue by masuero** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-masuero#2]
Hola Tali!
Por aquí una estudiante imprudente preguntando en vísperas de año nuevo. 
Cuando uno la variable creada para la discapacidad con la variable de los municipios me sale de la siguiente forma.
![image](https://user-images.githubusercontent.com/39682213/71609149-9a10cf80-2b5c-11ea-9988-902a98c80681.png).
Me genera x e y como sufijos de algunas columnas. No se si esta relacionado al tipo de objeto. Cuando consulto con la función class las variables me salen como "sf"  "data.frame" la de municipio, y la de discapacidad como "spec_tbl_df" "tbl_df"      "tbl"         "data.frame". 
Puedo crear una nueva variable seleccionando las columnas de x o de y, o debo corregir el problema en el origen de los datos?

**Comment by geofis** [comment]
El tali de este lado.

Los sufijos *x* e *y* significan que tanto el objeto fuente (`mun.sf`), como el que viene a unirse (`disc`), tienen columnas con nombres iguales. Por ejemplo, hay una columna `PROV` en el primero, y otra `PROV` en el segundo. Para evitarlo, puedes deshacerte de dichas columnas redundantes en el objeto `disc`, quedándote sólo con la que se hará la unión (`ENLACE`) y las de datos de discapacidad y tumbando la geometría, por ejemplo:

```disc.mun <- mun.sf %>% inner_join(disc %>% select(-(PROV:TOPONIMIA)) %st_drop_geometry, by = 'ENLACE')```

**Comment by masuero** [comment]
Saludos Profesor, 
Gracias por la respuesta. Al ejecutar la sentencia tuve problemas con la parte de st_drop_geometry, el error me decia que solo se podia aplicar a sf, lo quite y se ejecutó correctamente, así que seguí avanzando.
Pero otro problema que se me ha presentado es que cuando trato de generar el histograma o los mapas con ggplot cuando selecciono el nombre de la columna que contiene los datos de la discapacidad me genera error, aparenta no entender la palabra _ocupacional_ porque la subraya. Ya renombré la columna quitándole los dos puntos, pues pensaba que el simbolo era el problema pero sigue dando error, cuando me coloco encima de la palabra ocupacional me dice unexpected token. 
![image](https://user-images.githubusercontent.com/39682213/71706958-dabb5380-2dbd-11ea-8530-201e64a56665.png)

**Comment by geofis** [comment]
Prueba:

```
hist(disc.mun$`Categoría Ocupacional Discapacidado`)
```

R no reconoce variables con espacios a menos que se las encierre entre tildes.

**Comment by masuero** [comment]
Ayuda suministrada.
