### ISSUE TITLE
Ayuda con la función para Modelización

### ISSUE THREAD

**Issue by masuero** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-masuero#3]
Buenas Tardes Tali, 
Le escribo porque cuando estoy ejecutando el modelo espacial autorregresivo, el sistema me da una advertencia acerca de que la función fue movida de paquete, las imágenes son las siguientes:
![image](https://user-images.githubusercontent.com/39682213/72225797-f6fa8580-355f-11ea-9a1e-f3a168259e25.png)
![image](https://user-images.githubusercontent.com/39682213/72225807-10033680-3560-11ea-9781-1d2ad4b6b711.png)
Sin embargo cuando intento instalar el paquete dice que no existe:
![image](https://user-images.githubusercontent.com/39682213/72225822-3aed8a80-3560-11ea-82dc-f22b4c53f348.png)

El modelo se ejecutó a pesar de la advertencia, puedo seguir e ignorar el warning?

**Comment by geofis** [comment]
Puedes ignorar la advertencia. El autor del paquete creó el nuevo que te recomiendan, pero por el momento puedes seguir usando el antiguo.

**Comment by masuero** [comment]
Gracias por la respuesta profesor.
Ya estoy trabajando con la parte de la geoestadistica con los datos de precipitaciones, sin embargo se me esta presentando un problema con el Coordinate Reference System.
¿Porqué aunque haya asignado el sistema en UTM me sigue colocando las coordenadas geográficas?:
![image](https://user-images.githubusercontent.com/39682213/72230280-b19f7d80-358a-11ea-9877-5ef935202796.png)
Cuando cargué los datos al proyecto el epsg y el proj4string me salieron como N/A y le asigné el sistema de referencia de esta forma: 
st_crs(pre) <- "+proj=utm +zone=19 +datum=WGS84 +units=m +no_defs"
st_crs(pre) <- 32619
Cuando trato de generar los mapas el pais sale en un lado y los datos en otro.

**Comment by geofis** [comment]
El fallo viene al intentar asignar, no transformar. Para un objeto que no tiene asignado su CRS, se usa `st_crs`. Para un objeto al que le queremos transformar su CRS usamos `st_transform`. Si el archivo original viene en 4326 y deseas tenerlo en 32619, lo que aplicaría sería usar `st_transform`.

**Comment by masuero** [comment]
Es que cuando utilicé _st_transform_ me dijo que el objeto debia tener un CRS asociado. Cuando consulto me salen el epsg y el proj4string como N/A. 
Estoy leyendo los datos de la siguiente forma:
rutapre <- 'DATA/onamet_prec_anual_sf.gpkg'
pre <- st_read(rutapre)
st_crs(pre) <- "+proj=utm +zone=19 +datum=WGS84 +units=m +no_defs"
st_crs(pre) <- 32619

**Comment by geofis** [comment]
Pues correspondía entonces hacer `st_crs(pre) <- 4326`, que asigna el CRS correcto al objeto, y luego `preutm <- st_transform(pre, 32619)`
