### ISSUE TITLE
Fuente de los Datos

### ISSUE THREAD

**Issue by masuero** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-masuero#4]
Saludos profesor, 

A los fines de citar la fuente de los datos, me podría indicar si los datos que se encuentran en el repositorio _datos-para-proyectos_ corresponden a la encuesta ENHOGAR 2017? En el repositorio no indica que son datos extraídos de allí, pero sé que estos han sido los datos sobre los que hemos realizado otras asignaciones.

**Comment by geofis** [comment]
Los del repo son de dos fuentes:

IX Censo Nacional de Población y Vivienda, 2010.

No lo coloqué en el repo, pero lo actualizaré para que incluya la referencia. La URL central de dicho censo parece ser [ésta](https://censo2010.one.gob.do/)

**Comment by masuero** [comment]
Gracias por la respuesta!
