### ISSUE TITLE
Problema al tejer

### ISSUE THREAD

**Issue by masuero** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-masuero#5]
Saludos Profesor,

Estoy teniendo dificultades para tejer el documento del proyecto final, me presenta el siguiente error:
![image](https://user-images.githubusercontent.com/39682213/72583547-13c6ee00-38bd-11ea-9b65-4f5f52f3e216.png)

He hecho de todo, ya instalé y reinstalé el tinytex y aún continua el error.

**Comment by geofis** [comment]
El problema se generó al añadir el encabezado, que no estaba en la plantilla original:

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse=TRUE,
  out.width='100%',
  fig.path = "img/",
  dev = 'png',
  eval = T
)
```

Intenta tejer ahora.

**Comment by masuero** [comment]
Saludos Profesor, 

Sigo teniendo problemas, me genera el siguiente error:

![image](https://user-images.githubusercontent.com/39682213/72617605-b90ab200-390f-11ea-9a7e-6dd7c6c4e1e1.png)
El encabezado se encuentra de la siguiente forma:

![image](https://user-images.githubusercontent.com/39682213/72618068-b5c3f600-3910-11ea-9242-e1755c352f74.png)

Lo del tiny tex se lo he agregado luego de los errores que me ha presentado.

**Comment by geofis** [comment]
Lo que ves en el recuadro rojo, debes borrarlo:

![image](https://user-images.githubusercontent.com/13460617/72618526-a5f8e180-3911-11ea-8aaf-61f2ecc525e6.png)

**Comment by masuero** [comment]
Gracias profesor ya pude tejer, sin embargo ahora no me he podido identificar en el rstudio para poder hacer push del documento en git hub.  La terminal me aparece vacía no me deja escribir nada. Ya he abierto y cerrado la sesión en github y nada. 

![image](https://user-images.githubusercontent.com/39682213/72634957-157ec900-3932-11ea-87d8-c34ae847b175.png)

**Comment by geofis** [comment]
Hice la autentificación por ti. Prueba.

**Comment by masuero** [comment]
Listo profesor!
Muchas gracias por su disposición y por la ayuda brindada para resolver los incidentes.
